@rootURL = http://localhost:5209


GET {{rootURL}}/api/Users/
Accept: application/json

###

GET {{rootURL}}/api/Users/Yousef%40gmail.com
Accept: application/json

###

POST {{rootURL}}/api/Users
Content-Type: application/json

{ 
  "Email" : "Mohamed@gmail.com",
  "Name" : "mohamed",
  "Password" : "password123"
}

###

PUT {{rootURL}}/api/Users/102
Content-Type: application/json

{
  "UserID" : 102,
  "Email" : "Ashraf@gmail.com",
  "Name" : "Ashraf",
  "Password" : "passwd"
}

###

DELETE {{rootURL}}/api/Users/100

