CREATE DATABASE Cafeteria;
USE Cafeteria;

CREATE TABLE Users (
UserID INT PRIMARY KEY IDENTITY(100,1),
Email VARCHAR(30),
Name VARCHAR(20),
Passwords VARCHAR(20)
);

CREATE TABLE Orders (
OrderID INT PRIMARY KEY IDENTITY(1,1),
OrderDate DATETIME DEFAULT GETDATE(),
Amount INT
);

CREATE TABLE Wallet (
WalletID INT PRIMARY KEY IDENTITY(100,1),
UserID INT ,
Balance DECIMAL(10,2),
CONSTRAINT FK_Wallet_Users FOREIGN KEY (UserID) REFERENCES Users(UserID)ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Comment (
CommentID INT PRIMARY KEY IDENTITY(1,1),
OrderID INT,
Timestamp DATETIME DEFAULT GETDATE(),
TextContent VARCHAR(100),
CONSTRAINT FK_Comment_Orders FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Category (
CatID INT PRIMARY KEY IDENTITY(1,1),
CatName VARCHAR(25)
);

CREATE TABLE Menu (
MenuItemsID INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(20), ItemName VARCHAR(50),
CatID INT,
CONSTRAINT FK_Menu_Cat FOREIGN KEY (CatID) REFERENCES Category(CatID)
);

CREATE TABLE OrderItems (
ItemsID INT PRIMARY KEY IDENTITY(1,1),
MenuID INT,
Total DECIMAL(10,2),
Quantity INT,
CONSTRAINT ID_IN_MENU FOREIGN KEY (MenuID) REFERENCES MENU(MenuItemsID)
);

CREATE TABLE Order_Items_Link (
OrderID INT, 
ItemsID INT,
CONSTRAINT FK_Contains_Orders FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FK_Contains_OrderItems FOREIGN KEY (ItemsID) REFERENCES OrderItems(ItemsID)
);

CREATE TABLE OrderFrom (
MenuItemsID INT,
ItemsID INT,
CONSTRAINT FK_OrderFrom_Menu FOREIGN KEY (MenuItemsID) REFERENCES Menu(MenuItemsID) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FK_OrderFrom_OrderItems FOREIGN KEY (ItemsID) REFERENCES OrderItems(ItemsID)
);

CREATE TABLE Storage (
ItemID INT PRIMARY KEY IDENTITY(1,1),
LastRestocked DATE,
Available_Item VARCHAR(50)
);

CREATE TABLE ContainsFrom (
ItemID INT,
MenuItems INT,
CONSTRAINT FK_ContainsFrom_Storage FOREIGN KEY (ItemID) REFERENCES Storage(ItemID),
CONSTRAINT FK_ContainsFrom_Menu FOREIGN KEY (MenuItems) REFERENCES Menu(MenuItemsID)
);

CREATE TABLE Transactions (
TransactionsID INT PRIMARY KEY IDENTITY(1,1),
WalletID INT,
Date DATETIME DEFAULT GETDATE(), Amount DECIMAL(10,2),
Type VARCHAR(15),
CONSTRAINT FK_Transactions_Wallet FOREIGN KEY (WalletID) REFERENCES Wallet(WalletID) ON DELETE CASCADE ON UPDATE CASCADE
);